---
title: "Political violence"
author: "Kateryna Olkhovyk"
description: "how the number of anti-government demonstrations relate to the amount of extraconstitutional or forced changes in the top government"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts



## Does the number of anti-government demonstrations relate to the amount of extraconstitutional or forced changes in the top government? In this project, I plan to examine the relationship between peaceful gatherings in different countries and how their amount correlates with the forced changes on the level of the top authorities. From first glance it would seem that this would be the logical assumtion. I want to determine if this is really the case. I will use the data set "Political Violence" to determine this. I hypothesize that the rise of anti-government demonstrations raises the probability of a transition of state power, which means that the higher amount of protests result in a higher number of extraconstitutional changes in the selected countries. That implies that the more people come out and declare their demands in terms of government change, the higher the probability of meeting those demands. I expect that the results might be slightly different for different countries due to the number of citizens, political different regimes, and social activism culture. My sample comprises 209 government structures, which are my units of analysis. The explanatory variable of interest (agovdem 60, 70, 80) is the amount of peaceful public gatherings of at least 100 people over the three decades (60-the 80s). The variable is coded by the number of protests in each decade separately. My outcome variable is the count of extraconstitutional or forced changes in the top government (coups60, 70, 80). This variable is coded by the number of governmental changes. If I observe a greater number of governmental changes, this will provide support for my hypothesis and prove that the amount of peaceful demonstrations correlates with changes on the top state level. 


